export { RegistrationModule } from './RegistrationModule'
export { AuthModule } from './AuthModule'
export { AppModule } from './AppModule'
export { VMListModule } from './VMListModule'
export { VMInfoModule } from './VMInfoModule'
export { ProfileModule } from './ProfileModule'
